---
toolchain:
  - changed-files:
      - any-glob-to-any-file:
          - "flake.lock"
          - "flake.nix"
          - ".github/**"
          - ".githooks/**"
          - ".processes/**"
          - "scripts/**"
          - "rust-toolchain.toml"
          - ".coderabbit.yaml"
dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "Cargo.lock"
          - "**/Cargo.toml"
          - "uv.lock"
documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**"
crate:hopr-lib:
  - changed-files:
      - any-glob-to-any-file: hopr/hopr-lib/**
crate:hopr-metrics:
  - changed-files:
      - any-glob-to-any-file: misc/metrics/**
crate:hopr-platform:
  - changed-files:
      - any-glob-to-any-file: misc/platform/**
crate:hopr-transport:
  - changed-files:
      - any-glob-to-any-file: transport/api/**
crate:hopr-transport-mixer:
  - changed-files:
      - any-glob-to-any-file: transport/mixer/**
crate:hopr-transport-p2p:
  - changed-files:
      - any-glob-to-any-file: impls/transport/p2p/**
crate:hopr-transport-probe:
  - changed-files:
      - any-glob-to-any-file: transport/probe/**
crate:hopr-transport-protocol:
  - changed-files:
      - any-glob-to-any-file: transport/protocol/**
crate:hopr-transport-session:
  - changed-files:
      - any-glob-to-any-file: transport/session/**
