YARNFLAGS :=
CARGOFLAGS :=

ifeq ($(package),)
	YARNFLAGS := ${YARNFLAGS} -A
else
	YARNFLAGS := ${YARNFLAGS} ${package}
endif

ifneq ($(origin PRODUCTION),undefined)
	YARNFLAGS := ${YARNFLAGS} --production
endif

ifneq ($(origin CI),undefined)
	CARGOFLAGS := ${CARGOFLAGS} --locked
endif

.PHONY: deps
deps: ## install dependencies in CI
	yarn workspaces focus ${YARNFLAGS}
	cargo fetch --target wasm32-unknown-unknown ${CARGOFLAGS}