export const PRIVATE_KEY_LENGTH = 32
export const PUBLIC_KEY_LENGTH = 33
export const UNCOMPRESSED_PUBLIC_KEY_LENGTH = 66
export const ADDRESS_LENGTH = 20
export const HASH_LENGTH = 32
export const SIGNATURE_LENGTH = 64
export const SIGNATURE_RECOVERY_LENGTH = 1
