// NOTE: This is a hacky workaround for the fact that types were originally just in package `utils`
// and now they are between the `utils` and `core`.
// The TS code expects types to be in package `utils`
// This hack can be removed once more code in other packages is fully migrated to Rust

import { registerMetricsCollector } from './index.js'

import { hoprd_hoprd_initialize_crate, hoprd_hoprd_gather_metrics } from '../../hoprd/lib/hoprd_hoprd.js'
hoprd_hoprd_initialize_crate()
registerMetricsCollector(hoprd_hoprd_gather_metrics)

import { webcrypto } from 'node:crypto'

// @ts-ignore
globalThis.crypto = webcrypto

// Generated with: sed -En 's/^export ((class)|(enum)|(function)) ([A-Za-z0-9_]+).+$/\5,/p' hoprd_hoprd.d.ts | sort | grep -vE "(initialize)|(panic)"
export {
  AccountEntry,
  AcknowledgedTicket,
  Acknowledgement,
  Address,
  AnnouncementData,
  ApplicationData,
  AsyncIterableHelper,
  AsyncIterableHelperCoreHeartbeat,
  AsyncIterableHelperMixer,
  AuthorizationToken,
  Balance,
  BalanceType,
  ChainCalls,
  ChainKeypair,
  Challenge,
  ChannelEntry,
  ChannelStatus,
  channel_status_to_number,
  channel_status_to_string,
  CoreEthereumConstants,
  CORE_ETHEREUM_CONSTANTS,
  core_mixer_gather_metrics,
  core_network_gather_metrics,
  core_packet_gather_metrics,
  create_counter,
  create_gauge,
  create_histogram,
  create_histogram_with_buckets,
  create_multi_counter,
  create_multi_gauge,
  create_multi_histogram,
  create_multi_histogram_with_buckets,
  CurvePoint,
  Database,
  db_sanity_test,
  derive_commitment_seed,
  derive_mac_key,
  derive_packet_tag,
  EthereumChallenge,
  ethereum_signed_hash,
  gather_all_metrics,
  generate_channel_id,
  generate_ping_response,
  get_package_version,
  HalfKey,
  HalfKeyChallenge,
  Handlers,
  Hash,
  Health,
  health_to_string,
  HeartbeatConfig,
  hoprd_hoprd_gather_metrics,
  HoprKeys,
  IdentityOptions,
  is_allowed_to_access_network,
  IteratorResult,
  KeyBinding,
  KeyPair,
  merge_encoded_metrics,
  MessageInbox,
  MessageInboxConfiguration,
  MixerConfig,
  MultiCounter,
  MultiGauge,
  MultiHistogram,
  Network as PeerNetwork,
  new_mixer,
  number_to_channel_status,
  OffchainKeypair,
  OffchainPublicKey,
  OffchainSignature,
  PacketInteractionConfig,
  PassiveStrategy,
  Path,
  Payload,
  PeerOrigin,
  PeerStatus,
  PendingAcknowledgement,
  Ping,
  Pinger,
  PromiscuousStrategy,
  PublicKey,
  random_big_integer,
  random_bounded_integer,
  random_fill,
  random_float,
  random_integer,
  RandomStrategy,
  redeem_ticket,
  reply_to_ping,
  Response,
  Signature,
  SimpleCounter,
  SimpleGauge,
  SimpleHistogram,
  SimpleTimer,
  Snapshot,
  StrategyTickResult,
  Ticket,
  U256,
  UnacknowledgedTicket,
  WasmAckInteraction,
  WasmNetworkApi,
  WasmPacketInteraction,
  WasmPingApi,
  WasmVecAccountEntry,
  WasmVecAcknowledgedTicket,
  WasmVecAddress,
  WasmVecChannelEntry
} from '../../hoprd/lib/hoprd_hoprd.js'
