---
blokli_url: https://blokli.prod.hoprnet.link
identity:
  file: "/app/hoprd/conf/hopr.id"
db:
  data: /app/hoprd/data
api:
  enable: true
  host:
    address:
      IPv4: 0.0.0.0
    port: 3001
strategy:
  on_fail_continue: true
  allow_recursive: false
  strategies:
    - AutoRedeeming:
        redeem_all_on_close: true
        minimum_redeem_ticket_value: "1 wxHOPR"
        redeem_on_winning: true
    - ClosureFinalizer:
        max_closure_overdue: 300s
hopr:
  host:
    address:
      IPv4: 127.0.0.1 # NOTE: adapt this to reflect your public IP
    port: 9091 # NOTE: adapt this to reflect your public PORT - the value set in HOPRD_P2P_PORT
  safe_module:
    safe_address: "0x0000000000000000000000000000000000000000" # NOTE: fill in value
    module_address: "0x0000000000000000000000000000000000000000" # NOTE: fill in value
