export declare const CRAWLING_RESPONSE_NODES = 10;
export declare const PACKET_SIZE = 500;
export declare const MAX_HOPS = 3;
export declare const MARSHALLED_PUBLIC_KEY_SIZE = 37;
export declare const NAME = "ipfs";
export declare const PROTOCOL_STRING: string;
export declare const PROTOCOL_ACKNOWLEDGEMENT: string;
export declare const PROTOCOL_CRAWLING: string;
export declare const PROTOCOL_PAYMENT_CHANNEL: string;
export declare const PROTOCOL_DELIVER_PUBKEY: string;
export declare const PROTOCOL_ONCHAIN_KEY: string;
export declare const PROTOCOL_SETTLE_CHANNEL: string;
export declare const PROTOCOL_STUN: string;
export declare const PROTOCOL_HEARTBEAT: string;
export declare const PROTOCOL_WEBRTC_TURN_REQUEST: string;
export declare const PROTOCOL_WEBRTC_TURN: string;
export declare const PROTOCOL_FORWARD: string;
export declare const DEFAULT_STUN_PORT = 3478;
