Vagrant.configure("2") do |config|

  # on macOS M1 machines we must use the arm64 image
  arch = %x( uname -m )
  if arch.match(/arm64/) then
    config.vm.box = "generic/ubuntu2004-arm64"
  else
    config.vm.box = "generic/ubuntu2004"
  end

  # shared configuration for all VMs
  config.vm.provision "shell", path: "setup-vm.sh", privileged: true
  config.vm.synced_folder "../../", "/opt/hopr"

  config.vm.provider :libvirt do |v, override, libvirt|
    # Use NFS export on Linux
    config.vm.synced_folder "../../", "/opt/hopr", type: "nfs"
    # No need for any remote desktop environment
    libvirt.graphics_type = "none"
  end

  config.vm.define "hoprd-hardhat" do |hat|
    hat.vm.hostname = "hardhat.box"
    hat.vm.network "private_network", ip: "192.168.101.10"

    hat.vm.synced_folder "/tmp/hopr-identities", "/var/hopr/identities", create: true

    hat.vm.provision "file", source: "startup-network.sh", destination: "startup-network.sh"
    hat.vm.provision "file",  source: "faucet.sh", destination: "faucet.sh"
    hat.vm.provision "shell",  inline: "./startup-network.sh"
  end

  config.vm.define "hoprd-public-nodes" do |pub|
    pub.vm.hostname = "public.box"
    pub.vm.network "private_network", ip: "192.168.101.15"

    pub.vm.synced_folder "/tmp/hopr-identities", "/var/hopr/identities", create: true

    pub.vm.provision "shell", inline: "docker network create -d ipvlan --subnet=192.168.101.0/24 --ip-range=192.168.101.16/30 -o ipvlan_mode=l2 -o parent=eth1 hoprd-isolated || :", privileged: true
    pub.vm.provision "file",  source: "docker-compose-pub.yaml", destination: "docker-compose.yaml"
    pub.vm.provision "file",  source: "docker-runner/", destination: "docker-runner"
    pub.vm.provision "file",  source: "startup-hoprd-nodes.sh", destination: "startup-hoprd-nodes.sh"
    pub.vm.provision "shell",  inline: "./startup-hoprd-nodes.sh"
  end

  config.vm.define "hoprd-nat-nodes" do |nat|
    nat.vm.hostname = "nat-nodes.box"
    nat.vm.network "private_network", ip: "192.168.101.20"

    nat.vm.synced_folder "/tmp/hopr-identities", "/var/hopr/identities", create: true

    nat.vm.provision "file",  source: "docker-compose-nat.yaml", destination: "docker-compose.yaml"
    nat.vm.provision "file",  source: "docker-runner/", destination: "docker-runner"
    nat.vm.provision "file",  source: "startup-hoprd-nodes.sh", destination: "startup-hoprd-nodes.sh"
    nat.vm.provision "shell",  inline: "./startup-hoprd-nodes.sh"
  end
end
