/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface Ierc1820ImplementerContract
  extends Truffle.Contract<Ierc1820ImplementerInstance> {
  "new"(
    meta?: Truffle.TransactionDetails
  ): Promise<Ierc1820ImplementerInstance>;
}

type AllEvents = never;

export interface Ierc1820ImplementerInstance extends Truffle.ContractInstance {
  canImplementInterfaceForAddress(
    interfaceHash: string,
    account: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  methods: {
    canImplementInterfaceForAddress(
      interfaceHash: string,
      account: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
