//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ticket_statistics")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub channel_id: String,
    pub last_updated: Option<DateTimeUtc>,
    pub winning_tickets: i32,
    #[sea_orm(column_type = "Binary(12)")]
    pub redeemed_value: Vec<u8>,
    #[sea_orm(column_type = "Binary(12)")]
    pub neglected_value: Vec<u8>,
    #[sea_orm(column_type = "Binary(12)")]
    pub rejected_value: Vec<u8>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
