"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.HASH_LENGTH = 32;
exports.SIGNATURE_LENGTH = 64;
exports.NETWORK = 'testnet';
exports.CHAIN_NAME = 'ethereum';
exports.SIGNATURE_RECOVERY_LENGTH = 1;
exports.PRIVATE_KEY_LENGTH = 32;
exports.COMPRESSED_PUBLIC_KEY_LENGTH = 33;
exports.ADDRESS_LENGTH = 20;
