import AccountId from './accountId';
import Balance from './balance';
import Channel, { ChannelStatus } from './channel';
import ChannelBalance from './channelBalance';
import ChannelEntry from './channelEntry';
import ChannelId from './channelId';
import Hash from './hash';
import Moment from './moment';
import NativeBalance from './nativeBalance';
import PreImage from './preImage';
import Public from './public';
import Signature from './signature';
import SignedChannel from './signedChannel';
import SignedTicket from './signedTicket';
import State from './state';
import Ticket from './ticket';
import TicketEpoch from './ticketEpoch';
declare class Types {
    AccountId: typeof AccountId;
    Balance: typeof Balance;
    Channel: typeof Channel;
    ChannelBalance: typeof ChannelBalance;
    ChannelEntry: typeof ChannelEntry;
    ChannelId: typeof ChannelId;
    Hash: typeof Hash;
    Moment: typeof Moment;
    NativeBalance: typeof NativeBalance;
    PreImage: typeof PreImage;
    Public: typeof Public;
    Signature: typeof Signature;
    SignedChannel: typeof SignedChannel;
    SignedTicket: typeof SignedTicket;
    State: typeof State;
    Ticket: typeof Ticket;
    TicketEpoch: typeof TicketEpoch;
}
export { AccountId, Balance, Channel, ChannelId, ChannelBalance, ChannelEntry, ChannelStatus, Hash, Moment, NativeBalance, PreImage, Public, State, Signature, SignedChannel, SignedTicket, Ticket, TicketEpoch, };
export default Types;
