{
 "title": "HOPR Node Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Peers & Connectivity information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Peers by quality",
   "type": "timeseries",
   "description": "The number of high & low-quality peers your node is connected to.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(quality) (core_mgauge_peers_by_quality)",
     "legendFormat": "Number of {{quality}} quality peers"
    },
    { "expr": "core_gauge_num_peers", "legendFormat": "Total peers" }
   ]
  },
  {
   "title": "Relay connections",
   "type": "timeseries",
   "description": "Connections to and from public relay nodes.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "connect_gauge_relayed_conns", "legendFormat": "Number of relayed connections" },
    { "expr": "connect_gauge_conns_to_relays", "legendFormat": "Number of connected PRNs" }
   ]
  },
  {
   "title": "Graph description",
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "options": {
    "content": "This graph separates your peers into low (quality =< 0.5)  and high-quality (> 0.5) connections.\n\nThe quality of your connection to a peer is standardised between 0 to 1, depending on the ratio of successful pings to the total number of pings, regardless of who is sending them. \n"
   }
  },
  {
   "title": "Graph description",
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "options": {
    "content": "This graph represents the number of public relay nodes (PRN) you are connected to (yellow line) and if you are a PRN, the number of nodes you are connected to.\n\nIf you are not a PRN, the green line should be flat.\n"
   }
  },
  {
   "title": "Network health",
   "type": "state-timeline",
   "description": "History of your node’s connectivity status.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "targets": [
    { "expr": "core_gauge_network_health", "legendFormat": "Health" }
   ]
  },
  {
   "title": "Ping rates",
   "type": "timeseries",
   "description": "The number of successful and unsuccessful pings your node sends per second.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "rate(core_counter_heartbeat_successful_pings[$__rate_interval])",
     "legendFormat": "Rate of successful pings"
    },
    {
     "expr": "rate(core_counter_heartbeat_failed_pings[$__rate_interval])",
     "legendFormat": "Rate of failed pings"
    }
   ]
  },
  {
   "title": "Graph description",
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 24 },
   "options": {
    "content": "This displays your network connectivity status over time (x-axis).\n\nYour connection can be one of five states:\n- **Unknown (Grey)**: The network could not assess your node's connection.\n- 🔴 **Red**: You have no connection to the network at all.\n- 🟠 **Orange**: At least one low-quality connection to a public relay node.\n- 🟡 **Yellow**: At least one high-quality connection to a public relay node.\n- 🟢 **Green**: At least one high-quality connection to a public relay node and one non-public node.\n"
   }
  },
  {
   "title": "Graph description",
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 24 },
   "options": {
    "content": "This graph shows the number of successful (blue) and unsuccessful (red) pings your node sends per second.\n\nThese are pings counted from your node's heartbeat.\n"
   }
  },
  {
   "title": "Total heartbeat probing time",
   "type": "bargauge",
   "description": "The time it takes your node to complete a heartbeat probing cycle.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "core_histogram_heartbeat_time_seconds_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Ping response time",
   "type": "bargauge",
   "description": "Response time for pings sent by your node in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "core_histogram_ping_time_seconds_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Graph description",
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 37 },
   "options": {
    "content": "This shows the total time it takes your node to complete a probing cycle. E.g. how long it takes your node to successfully ping all of its known peers. "
   }
  },
  {
   "title": "Graph description",
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 37 },
   "options": {
    "content": "This shows the spread of the response time for your pings rounded to the nearest interval. \n\nThis is specifically the response time for pings sent by your node as part of the heartbeat mechanism.\n"
   }
  },
  {
   "title": "Network metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Message statistics",
   "type": "stat",
   "description": "Basic statistics on sent/received/forwarded HOPR messages by this node.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "core_counter_sent_messages", "legendFormat": "Sent messages" },
    { "expr": "core_counter_received_messages", "legendFormat": "Received messages" },
    {
     "expr": "core_counter_forwarded_messages",
     "legendFormat": "Forwarded  messages"
    }
   ]
  },
  {
   "title": "Channels",
   "type": "stat",
   "description": "Numbers of incoming/outgoing payment channels",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "core_gauge_num_incoming_channels",
     "legendFormat": "Number of incoming channels"
    },
    {
     "expr": "core_gauge_num_outgoing_channels",
     "legendFormat": "Number of outgoing channels"
    }
   ]
  },
  {
   "title": "Hourly message rates",
   "type": "timeseries",
   "description": "Rate of messages per hour .",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "rate(core_counter_received_messages[1h])",
     "legendFormat": "Rate of received messages"
    },
    {
     "expr": "rate(core_counter_sent_messages[1h])",
     "legendFormat": "Rate of sent messages"
    },
    {
     "expr": "rate(core_counter_forwarded_messages[1h])",
     "legendFormat": "Rate of forwarded messages"
    }
   ]
  },
  {
   "title": "Tickets",
   "type": "stat",
   "description": "Number of winning/losing tickets.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "core_counter_winning_tickets", "legendFormat": "Winning tickets" },
    { "expr": "core_counter_losing_tickets", "legendFormat": "Losing tickets" }
   ]
  },
  {
   "title": "V8 metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Used heap",
   "type": "timeseries",
   "description": "Amount of heap used by V8 engine in Node.js runtime.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "hoprd_gauge_nodejs_total_used_heap_bytes",
     "legendFormat": "Used heap"
    },
    {
     "expr": "avg_over_time(hoprd_gauge_nodejs_total_used_heap_bytes[1h])",
     "legendFormat": "Used heap (average over 1hr)"
    }
   ]
  },
  {
   "title": "Number of restarts",
   "type": "gauge",
   "description": "Number of times the node has restarted (either on user's request or due to error).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "changes(hoprd_gauge_startup_unix_time_seconds[$__range])"
    }
   ]
  },
  {
   "title": "Total available heap",
   "type": "timeseries",
   "description": "Total amount of heap available for V8 engine in Node.js runtime.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "hoprd_gauge_nodejs_total_available_heap_bytes",
     "legendFormat": "Total available heap"
    },
    {
     "expr": "avg_over_time(hoprd_gauge_nodejs_total_available_heap_bytes[1h])",
     "legendFormat": "Total available heap (average over 1hr)"
    }
   ]
  },
  {
   "title": "Node startup timestamp",
   "type": "timeseries",
   "description": "Timestamped view of node startup and restart.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "expr": "hoprd_gauge_startup_unix_time_seconds",
     "legendFormat": "Startup unix timestamp"
    }
   ]
  }
 ]
}