use thiserror::Error;

/// Errors that can be generated by the crate.
#[derive(Error, Debug)]
pub enum NetworkingError {
    #[error("performing an operation on own PeerId")]
    DisallowedOperationOnOwnPeerIdError,
    #[error("database or chain error: {0}")]
    DbChainError(Box<dyn std::error::Error + Send + Sync + 'static>),
}

/// Result built on top of the crate error [NetworkingError]
pub type Result<T> = core::result::Result<T, NetworkingError>;
