use thiserror::Error;

/// Errors that can be generated by the crate.
#[derive(Error, Debug)]
pub enum NetworkError {
    #[error("performing an operation on own PeerId")]
    DisallowedOperationOnOwnPeerIdError,
}

/// Result built on top of the crate error [`NetworkError`]
pub type Result<T> = core::result::Result<T, NetworkError>;
