/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from 'ethers'
import { Provider } from '@ethersproject/providers'

import type { Multicall } from '../Multicall'

export class Multicall__factory {
  static connect(address: string, signerOrProvider: Signer | Provider): Multicall {
    return new Contract(address, _abi, signerOrProvider) as Multicall
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: 'bytes[]',
        name: 'data',
        type: 'bytes[]'
      }
    ],
    name: 'multicall',
    outputs: [
      {
        internalType: 'bytes[]',
        name: 'results',
        type: 'bytes[]'
      }
    ],
    stateMutability: 'nonpayable',
    type: 'function'
  }
]
