// Length of hash values generated by the on-chain hash function
export const HASH_LENGTH: number

// Length of signatures that are used on-chain
export const SIGNATURE_LENGTH: number

// Name of the network, e.g. `mainnet` or `testnet`
export const NETWORK: string

// Name of the chain, e.g. `ethereum` or `polkadot`
export const CHAIN_NAME: string
