Vagrant.configure("2") do |config|
  
  config.vm.define "public" do |pub|
    pub.vm.box = "generic/ubuntu2004"
    pub.vm.hostname = "relay.box"
    pub.vm.network "private_network", ip: "192.168.101.10"

    #pub.vm.provision "file", source: "../..", destination: "/opt/hopr"

    pub.vm.provision "shell", path: "setup-vm.sh"
    pub.vm.synced_folder "../../", "/opt/hopr"
    pub.vm.synced_folder "/tmp/hopr-identities", "/var/hopr/identities", create: true
    pub.vm.provision "file", source: "startup-network.sh", destination: "startup-network.sh"

  end

  config.vm.define "nat_nodes" do |nat|
    nat.vm.box = "generic/ubuntu2004"
    nat.vm.hostname = "natnodes.box"
    nat.vm.network "private_network", ip: "192.168.101.20"

    #pub.vm.provision "file", source: "../..", destination: "/opt/hopr"

    nat.vm.provision "shell", path: "setup-vm.sh"
    nat.vm.synced_folder "../../", "/opt/hopr"
    nat.vm.synced_folder "/tmp/hopr-identities", "/var/hopr/identities", create: true

    nat.vm.provision "file",  source: "docker-compose.yaml", destination: "docker-compose.yaml"
    nat.vm.provision "file",  source: "Dockerfile", destination: "Dockerfile"
    #nat.vm.provision "shell", inline: "docker-compose up -d --force-recreate --remove-orphans"
  end

end
