---
name: Branches

on:
  push:
    branches:
      - master

permissions:
  contents: read

concurrency:
  group: branches-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  coverage:
    name: Coverage
    uses: hoprnet/hopr-workflows/.github/workflows/tests.yaml@268553d7984344080e3dc65eb92778c9103af7ec # workflow-tests-v3
    with:
      source_branch: ${{ github.ref_name }}
      unit_tests: false
      integration_tests: false
      nightly_tests: false
      benchmarks: false
      unit_coverage: true
      integration_coverage: true
      unconditional: true
      unit_coverage_command: |
        nix build -L .#coverage-unit
        cp result coverage.lcov
      integration_coverage_command: |
        nix develop .#coverage -c env NEXTEST_HIDE_PROGRESS_BAR=1 cargo llvm-cov nextest \
          --workspace \
          --test '*' \
          --lcov --output-path coverage.lcov \
          -j 1
      runner: self-hosted-hoprnet-bigger
    secrets:
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
