---
#################################################################################
# Build and publish rust documentation
#################################################################################
name: "Build docs"

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      source_repo:
        required: true
        type: string
      source_branch:
        required: true
        type: string
      publish:
        required: true
        type: boolean
        description: 'Publish the docs'
    secrets:
      CACHIX_AUTH_TOKEN:
        required: true

concurrency:
  group: ${{ inputs.source_branch || github.ref_name }}-docs
  cancel-in-progress: true

permissions:
  contents: write # for peaceiris/actions-gh-pages to push pages branch

jobs:
  rust:
    name: Rust
    # big runner is needed because building docs involves building Rust code
    runs-on: self-hosted-hoprnet-bigger
    timeout-minutes: 60
    steps:
      - name: Build docs
        uses: hoprnet/hopr-workflows/actions/nix-action@c2aca7e56d25c4a786049ccf816c7f1af8721de8 # nix-action-v1
        with:
          source_branch: ${{ inputs.source_branch }}
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          command: |
            set -e
            RUSTDOCFLAGS="-D warnings" nix develop -c cargo doc --no-deps --document-private-items
            nix build -L .#docs

      - name: Increase git buffer size
        if: inputs.publish
        run: git config --global http.postBuffer 524288000

      - name: Deploy
        if: inputs.publish
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./result/share/doc/
          force_orphan: true
