---
#################################################################################
##                      Pipeline to build on pull requests                     ##
#################################################################################
name: Build
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
concurrency:
  group: ${{ github.event.pull_request.head.ref || github.ref_name }}-build
  cancel-in-progress: true
permissions:
  contents: write
env:
  CARGO_TERM_COLOR: always
jobs:
  build-dappnode:
    strategy:
      fail-fast: false
      matrix:
        dappnode_repository:
          - DAppNodePackage-Hopr
          - DAppNodePackage-Hopr-testnet
    name: ${{ matrix.dappnode_repository }}
    needs:
      - build-docker
    uses: ./.github/workflows/build-dappnode.yaml
    with:
      source_repo: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
      source_branch: ${{ github.event.pull_request.head.ref || github.ref }}
      dappnode_repository: ${{ matrix.dappnode_repository }}
      labels: ${{ format('{0},', join(github.event.pull_request.labels.*.name, ',')) }}
    secrets: inherit
  build-binaries:
    name: Binary ${{ matrix.architecture }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - architecture: x86_64-linux
            runner: self-hosted-hoprnet-bigger
            build_command: nix build -L .#binary-hoprd-x86_64-linux
            required_label: ""
          - architecture: aarch64-linux
            runner: self-hosted-hoprnet-bigger
            build_command: nix build -L .#binary-hoprd-aarch64-linux
            required_label: "binary:aarch64-linux"
          - architecture: aarch64-darwin
            runner: macos-15-xlarge
            build_command: nix build -L .#binary-hoprd-aarch64-darwin
            required_label: binary:aarch64-darwin
          - architecture: x86_64-darwin
            runner: macos-15-intel
            build_command: nix build -L .#binary-hoprd-x86_64-darwin
            required_label: binary:x86_64-darwin
    uses: hoprnet/hopr-workflows/.github/workflows/build-binaries.yaml@build-binaries-v2
    permissions:
      contents: read
    with:
      source_branch: ${{ github.event.pull_request.head.ref || github.ref }}
      version_type: commit
      architecture: ${{ matrix.architecture }}
      cachix_cache_name: hoprnet
      build_file: hopr/hopr-lib/Cargo.toml
      build_command: ${{ matrix.build_command }}
      binary: hoprd
      runner: ${{ matrix.runner }}
      enabled: ${{ matrix.required_label == '' || contains(github.event.pull_request.labels.*.name, matrix.required_label) }}
    secrets:
      gcp_service_account: ${{ secrets.GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY }}
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      gpg_private_key: ${{ secrets.GPG_HOPRNET_PRIVATE_KEY }}
  build-docker:
    name: Docker
    uses: hoprnet/hopr-workflows/.github/workflows/build-docker.yaml@build-docker-v1
    needs: build-binaries
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    with:
      source_branch: ${{ github.event.pull_request.head.ref || github.ref }}
      version_type: commit
      build_matrix: >-
        [
          {
            "runner": "self-hosted-hoprnet-bigger",
            "architecture": "x86_64-linux",
            "build_command": "nix build -L .#docker-hoprd-x86_64-linux",
            "build_debug_command": "nix build -L .#docker-hoprd-dev-x86_64-linux"
          }
        ]
      cachix_cache_name: hoprnet
      build_file: hopr/hopr-lib/Cargo.toml
      docker_image_name: hoprd
      docker_image_format: skopeo
    secrets:
      gcp_service_account: ${{ secrets.GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY }}
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
  docs:
    name: Docs
    uses: ./.github/workflows/build-docs.yaml
    secrets: inherit
    with:
      source_repo: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
      source_branch: ${{ github.event.pull_request.head.ref || github.ref }}
      publish: false
