---
name: Cargo redundant deps

env:
  RUST_BACKTRACE: "1"

on:
  merge_group:
    types: [checks_requested]
  workflow_call:
    inputs:
      source_repo:
        required: true
        type: string
      source_branch:
        required: true
        type: string

concurrency:
  group: ${{ inputs.source_branch || github.ref_name }}-cargo-redundant-deps
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  detect-unused-dependencies:
    name: Redundant cargo dependencies
    runs-on: self-hosted-hoprnet-bigger
    timeout-minutes: 10
    steps:
      - name: Check cargo deps
        uses: hoprnet/hopr-workflows/actions/nix-action@290ac3c27a2735cd4860b4a1b41c515cdb5a1feb # nix-action-v1
        with:
          source_branch: ${{ inputs.source_branch }}
          use_cachix: "true"
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          command: nix develop .#ci -c bash -c "cargo machete && cargo shear"
