---
################################################################################
# Reusable check pipeline
################################################################################
name: Checks

on:
  workflow_call:
    inputs:
      source_repo:
        required: true
        type: string
      source_branch:
        required: true
        type: string
    secrets:
      CACHIX_AUTH_TOKEN:
        required: true

jobs:
  check:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    timeout-minutes: ${{ matrix.timeout }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Pre-commit
            runner: self-hosted-hoprnet-small
            timeout: 15
            command: nix build -L .#pre-commit-check
          - name: Lint
            runner: self-hosted-hoprnet-bigger
            timeout: 30
            command: nix run -L .#check
          - name: Cargo deps
            runner: self-hosted-hoprnet-bigger
            timeout: 10
            command: nix develop .#ci -c bash -c "cargo machete && cargo shear"
          - name: Audit
            runner: self-hosted-hoprnet-bigger
            timeout: 15
            command: nix run .#audit
    steps:
      - name: Run ${{ matrix.name }}
        uses: hoprnet/hopr-workflows/actions/nix-action@c2aca7e56d25c4a786049ccf816c7f1af8721de8 # nix-action-v1
        with:
          source_branch: ${{ inputs.source_branch }}
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          command: ${{ matrix.command }}
