---
################################################################################
# Reusable check pipeline
#
# Interface designed to match the future hopr-workflows/rust-checks.yaml.
################################################################################
name: Checks

on:
  workflow_call:
    inputs:
      source_branch:
        required: true
        type: string
      pre_commit:
        required: false
        type: boolean
        default: true
      lint:
        required: false
        type: boolean
        default: true
      cargo_deps:
        required: false
        type: boolean
        default: true
      audit:
        required: false
        type: boolean
        default: true
      pre_commit_command:
        required: false
        type: string
        default: "nix build -L .#pre-commit-check"
      lint_command:
        required: false
        type: string
        default: "nix run -L .#check"
      cargo_deps_command:
        required: false
        type: string
        default: 'nix develop .#ci -c bash -c "cargo machete && cargo shear"'
      audit_command:
        required: false
        type: string
        default: "nix run .#audit"
      runner_small:
        required: false
        type: string
        default: "ubuntu-latest"
      runner_large:
        required: false
        type: string
        default: "ubuntu-latest"
    secrets:
      cachix_auth_token:
        required: true

jobs:
  check:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    timeout-minutes: ${{ matrix.timeout }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Pre-commit
            enabled: ${{ inputs.pre_commit }}
            runner: ${{ inputs.runner_small }}
            timeout: 15
            command: ${{ inputs.pre_commit_command }}
          - name: Lint
            enabled: ${{ inputs.lint }}
            runner: ${{ inputs.runner_large }}
            timeout: 30
            command: ${{ inputs.lint_command }}
          - name: Cargo deps
            enabled: ${{ inputs.cargo_deps }}
            runner: ${{ inputs.runner_large }}
            timeout: 10
            command: ${{ inputs.cargo_deps_command }}
          - name: Audit
            enabled: ${{ inputs.audit }}
            runner: ${{ inputs.runner_large }}
            timeout: 15
            command: ${{ inputs.audit_command }}
    steps:
      - name: Run ${{ matrix.name }}
        if: matrix.enabled
        uses: hoprnet/hopr-workflows/actions/nix-action@c2aca7e56d25c4a786049ccf816c7f1af8721de8 # nix-action-v1
        with:
          source_branch: ${{ inputs.source_branch }}
          cachix_auth_token: ${{ secrets.cachix_auth_token }}
          command: ${{ matrix.command }}
