---
#################################################################################
# Pipeline triggered on every pull request to check lint compliance
#################################################################################
name: Lint

env:
  RUST_BACKTRACE: "1"

on:
  merge_group:
    types: [checks_requested]
  workflow_call:
    inputs:
      source_repo:
        required: true
        type: string
      source_branch:
        required: true
        type: string

concurrency:
  group: ${{ inputs.source_branch || github.ref_name }}-lint
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: self-hosted-hoprnet-bigger
    timeout-minutes: 30
    steps:
      - name: Run linter
        uses: hoprnet/hopr-workflows/actions/nix-action@04bef49c02b8d5407a49dc1de42d08e727086180
        with:
          repository: ${{ inputs.source_repo }}
          ref: ${{ inputs.source_branch }}
          use_cachix: "true"
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          command: nix run -L .#check
