---
name: Zizmor

on:
  merge_group:
    types: [checks_requested]
  workflow_call:
    inputs:
      source_repo:
        required: true
        type: string
      source_branch:
        required: true
        type: string

concurrency:
  group: ${{ inputs.source_branch || github.ref_name }}-zizmor
  cancel-in-progress: true

permissions:
  contents: read
  security-events: write

jobs:
  zizmor:
    name: Zizmor
    runs-on: self-hosted-hoprnet-bigger
    permissions:
      contents: read
      security-events: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Run zizmor
        uses: hoprnet/hopr-workflows/actions/nix-action@290ac3c27a2735cd4860b4a1b41c515cdb5a1feb # nix-action-v1
        with:
          source_branch: ${{ inputs.source_branch }}
          use_cachix: "true"
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          command: nix develop -L .#ci -c bash -c "zizmor --format sarif . > results.sarif"

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@89a39a4e59826350b863aa6b6252a07ad50cf83e # v4.32.4
        with:
          sarif_file: results.sarif
          category: zizmor
