---
name: Audit

on:
  merge_group:
    types: [checks_requested]
  workflow_call:
    inputs:
      source_repo:
        required: true
        type: string
      source_branch:
        required: true
        type: string

concurrency:
  group: ${{ inputs.source_branch || github.ref_name }}-audit
  cancel-in-progress: true

jobs:
  cargo-audit:
    name: Audit
    runs-on: self-hosted-hoprnet-bigger
    steps:
      - name: Run Audit
        uses: hoprnet/hopr-workflows/actions/nix-action@nix-action-v1
        with:
          source_branch: ${{ inputs.source_branch }}
          command: nix run .#audit
