---
################################################################################
# Main pipeline to run checks hoprnet
################################################################################
name: Checks

on:
  merge_group:
    types: [checks_requested]
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  actions: read
  security-events: write
  contents: read

concurrency:
  group: ${{ github.event.pull_request.head.ref || github.ref_name }}-checks
  cancel-in-progress: true

jobs:
  check:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    timeout-minutes: ${{ matrix.timeout }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Pre-commit
            runner: self-hosted-hoprnet-small
            timeout: 15
            command: nix build -L .#pre-commit-check
          - name: Lint
            runner: self-hosted-hoprnet-bigger
            timeout: 30
            command: nix run -L .#check
          - name: Cargo deps
            runner: self-hosted-hoprnet-bigger
            timeout: 10
            command: nix develop .#ci -c bash -c "cargo machete && cargo shear"
          - name: Audit
            runner: self-hosted-hoprnet-bigger
            timeout: 15
            command: nix run .#audit
    steps:
      - name: Run ${{ matrix.name }}
        uses: hoprnet/hopr-workflows/actions/nix-action@nix-action-v1
        with:
          source_branch: ${{ github.event.pull_request.head.ref || github.ref }}
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          command: ${{ matrix.command }}

  zizmor:
    name: Zizmor
    uses: ./.github/workflows/checks-zizmor.yaml
    with:
      source_repo: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
      source_branch: ${{ github.event.pull_request.head.ref || github.ref }}
    secrets: inherit
