---
name: Cleanup PR

on:
  workflow_dispatch:
    inputs:
      pr_number:
        type: number
        required: true
        description: "Pull request number"

jobs:
  cleanup-pr:
    name: Remove cache
    runs-on: depot-ubuntu-24.04
    permissions:
      actions: write
      contents: read
      id-token: write
    timeout-minutes: 10
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          disable-sudo: true
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout hoprnet repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          ref: master

      - name: Setup GCP
        id: gcp
        uses: hoprnet/hopr-workflows/actions/setup-gcp@7263182fc9a2bab22cc5a029929940914eb9748d # setup-gcp-v4
        with:
          login_artifact_registry: 'true'
          install_sdk: 'true'

      - name: Cleanup Github pipeline cache
        run: |
          mapfile -t cacheKeysForPR < <(gh actions-cache list -R "${REPO}" -B "refs/pull/${PR_NUMBER}/merge" --json key --jq '.[].key')
          for cacheKey in "${cacheKeysForPR[@]}"
          do
            gh actions-cache delete "$cacheKey" -R "${REPO}" -B "refs/pull/${PR_NUMBER}/merge" --confirm
          done
        env:
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.inputs.pr_number }}
