---
name: Cleanup PR

on:
  workflow_dispatch:
    inputs:
      pr_number:
        type: number
        required: true
        description: "Pull request number"

jobs:
  cleanup-pr:
    name: Remove cache
    runs-on: depot-ubuntu-24.04
    permissions:
      actions: write
      contents: read
      id-token: write
    timeout-minutes: 10
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          disable-sudo: true
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout hoprnet repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
          ref: master

      - name: Setup GCP
        id: gcp
        uses: hoprnet/hopr-workflows/actions/setup-gcp@ac3e0b6137b0ba470a30c373aab2ceba9e0879e4 # setup-gcp-v4
        with:
          login_artifact_registry: 'true'
          install_sdk: 'true'

      - name: Cleanup Github pipeline cache
        run: |
          mapfile -t cacheKeysForPR < <(gh actions-cache list -R "${REPO}" -B "refs/pull/${PR_NUMBER}/merge" | cut -f 1)
          for cacheKey in "${cacheKeysForPR[@]}"
          do
            gh actions-cache delete "$cacheKey" -R "${REPO}" -B "refs/pull/${PR_NUMBER}/merge" --confirm
          done
        env:
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.inputs.pr_number }}
