---
#################################################################################
# Pipeline generate the Yellowpaper
#################################################################################
name: Yellowpaper

on:
  push:
    branches:
      - 'master'
      - 'yellowpaper/**'
    paths:
      - '!docs/yellowpaper/yellowpaper.pdf'
      - 'docs/yellowpaper/**'
      - '.github/workflows/latexcompile.yaml'

permissions:
  contents: read

jobs:
  build_latex:
    runs-on: depot-ubuntu-24.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          disable-sudo: true
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Set up Git repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Configure Git info
        run: |
          git config user.email "tech@hoprnet.org"
          git config user.name "HOPR CI robot"
          git config pull.rebase false

      - name: Install dependencies
        run: >
          sudo apt -y install texlive texlive-latex-extra texlive-science texlive-bibtex-extra latexmk #magic___^_^___line
      - name: Compile LaTeX document
        run: make -j build-yellowpaper

      - name: Commit & Push changes
        uses: EndBug/add-and-commit@290ea2c423ad77ca9c62ae0f5b224379612c0321 # v10.0.0
        with:
          new_branch: ${{ github.ref }}
          message: 'chore(build): update yellowpaper'
          pathspec_error_handling: exitImmediately
