---
#################################################################################
# Manual pipeline to start a load testing scenario
#################################################################################
name: Load Tests

on:
  workflow_call:
    inputs:
      test_id:
        type: string
        required: true
      cluster_nodes:
        type: string
        required: true
      topology:
        type: string
        required: true
      workload:
        type: string
        required: true
      duration:
        type: number
        required: true
      echo_service_replicas:
        type: number
        required: true
      payload_size:
        type: number
        required: true
      download_throughput:
        type: number
        required: true
      upload_throughput:
        type: number
        required: true
  workflow_dispatch:
    inputs:
      test_id:
        type: string
        required: true
        description: 'Test name'
        default: 'load-test'
      cluster_nodes:
        type: choice
        options:
          - core-rotsee
          - gnosisvpn-staging
          - core-dufour
          - ctdapp-rotsee
          - demo-rotsee
          - team
        required: true
        description: 'Cluster of nodes to test'
      topology:
        type: choice
        options:
          - receiver
          - many2many
          - sender
          - relayer
        required: true
        description: 'Nodes channel topology'
      workload:
        type: choice
        options:
          - constant
          - incremental
          - hysteresis
          - sanity-check
          - multiple-hops
        required: true
        description: 'Workload type'
      duration:
        type: number
        default: 30
        required: true
        description: 'Test duration in minutes'
      echo_service_replicas:
        type: number
        default: 3
        required: true
        description: 'Echo service replicas'
      payload_size:
        type: number
        default: 1048576
        required: true
        description: 'Payload size in bytes'
      download_throughput:
        type: number
        default: 65536 # Baseline: 64kB/s # 512kbps
        required: true
        description: 'Download throughput in bytes per second (0 means disabled scenario)'
      upload_throughput:
        type: number
        default: 0
        required: true
        description: 'Upload throughput in bytes per second (0 means disabled scenario)'

concurrency:
  group: load-tests
  cancel-in-progress: true

jobs:
  load-tests:
    name: Load Tests
    permissions:
      contents: read
    runs-on: self-hosted-hoprnet-small
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          disable-sudo: true
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout hoprd-test repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          repository: hoprnet/hoprd-test
          ref: ${{ vars.K6_REPOSITORY_BRANCH_NAME || 'main' }}

      - name: Setup GCP
        id: gcp
        uses: hoprnet/hopr-workflows/actions/setup-gcp@644d936de4e1c8f5c50ba50f8526209455c28b4a # master
        with:
          google_credentials: ${{ secrets.GCP_SA_GITHUB_RUNNER }}
          login_artifact_registry: 'false'
          install_sdk: 'true'
          login_gke: 'true'
          project: hopr-staging
      - name: Set environment variables
        env:
          INPUT_TEST_ID: ${{ inputs.test_id }}
          INPUT_CLUSTER_NODES: ${{ inputs.cluster_nodes }}
          INPUT_TOPOLOGY: ${{ inputs.topology }}
          INPUT_WORKLOAD: ${{ inputs.workload }}
          INPUT_DURATION: ${{ inputs.duration }}
          INPUT_ECHO_SERVICE_REPLICAS: ${{ inputs.echo_service_replicas }}
          INPUT_PAYLOAD_SIZE: ${{ inputs.payload_size }}
          INPUT_DOWNLOAD_THROUGHPUT: ${{ inputs.download_throughput }}
          INPUT_UPLOAD_THROUGHPUT: ${{ inputs.upload_throughput }}
          EVENT_TEST_ID: ${{ github.event.inputs.test_id }}
          EVENT_CLUSTER_NODES: ${{ github.event.inputs.cluster_nodes }}
          EVENT_TOPOLOGY: ${{ github.event.inputs.topology }}
          EVENT_WORKLOAD: ${{ github.event.inputs.workload }}
          EVENT_DURATION: ${{ github.event.inputs.duration }}
          EVENT_ECHO_SERVICE_REPLICAS: ${{ github.event.inputs.echo_service_replicas }}
          EVENT_PAYLOAD_SIZE: ${{ github.event.inputs.payload_size }}
          EVENT_DOWNLOAD_THROUGHPUT: ${{ github.event.inputs.download_throughput }}
          EVENT_UPLOAD_THROUGHPUT: ${{ github.event.inputs.upload_throughput }}
        run: |
          if [ -z "${EVENT_TEST_ID}" ]; then
            echo "The workflow is triggered by other pipeline"
            {
              echo "TESTID=${INPUT_TEST_ID}"
              echo "K6_EXECUTION_NAME=${INPUT_TEST_ID}"
              echo "K6_CLUSTER_NODES=${INPUT_CLUSTER_NODES}"
              echo "K6_TOPOLOGY_NAME=${INPUT_TOPOLOGY}"
              echo "K6_WORKLOAD_NAME=${INPUT_WORKLOAD}"
              echo "K6_TEST_DURATION=${INPUT_DURATION}"
              echo "K6_ECHO_SERVERS_REPLICAS=${INPUT_ECHO_SERVICE_REPLICAS}"
              echo "K6_PAYLOAD_SIZE=${INPUT_PAYLOAD_SIZE}"
              echo "K6_DOWNLOAD_THROUGHPUT=${INPUT_DOWNLOAD_THROUGHPUT}"
              echo "K6_UPLOAD_THROUGHPUT=${INPUT_UPLOAD_THROUGHPUT}"
            } >> $GITHUB_ENV
          else
            echo "The workflow is triggered manually"
            {
              echo "TESTID=${EVENT_TEST_ID}"
              echo "K6_EXECUTION_NAME=${EVENT_TEST_ID}"
              echo "K6_CLUSTER_NODES=${EVENT_CLUSTER_NODES}"
              echo "K6_TOPOLOGY_NAME=${EVENT_TOPOLOGY}"
              echo "K6_WORKLOAD_NAME=${EVENT_WORKLOAD}"
              echo "K6_TEST_DURATION=${EVENT_DURATION}"
              echo "K6_ECHO_SERVERS_REPLICAS=${EVENT_ECHO_SERVICE_REPLICAS}"
              echo "K6_PAYLOAD_SIZE=${EVENT_PAYLOAD_SIZE}"
              echo "K6_DOWNLOAD_THROUGHPUT=${EVENT_DOWNLOAD_THROUGHPUT}"
              echo "K6_UPLOAD_THROUGHPUT=${EVENT_UPLOAD_THROUGHPUT}"
            } >> $GITHUB_ENV
          fi
          EFFECTIVE_DOWNLOAD="${INPUT_DOWNLOAD_THROUGHPUT:-${EVENT_DOWNLOAD_THROUGHPUT}}"
          if [[ "${EFFECTIVE_DOWNLOAD}" -eq 0 ]]; then
            echo "Download throughput is disabled"
            echo "K6_SKIP_SCENARIO_DOWNLOAD=true" >> $GITHUB_ENV
            echo "K6_DOWNLOAD_THROUGHPUT=524288" >> $GITHUB_ENV
          fi
          EFFECTIVE_UPLOAD="${INPUT_UPLOAD_THROUGHPUT:-${EVENT_UPLOAD_THROUGHPUT}}"
          if [[ "${EFFECTIVE_UPLOAD}" -eq 0 ]]; then
            echo "Upload throughput is disabled"
            echo "K6_SKIP_SCENARIO_UPLOAD=true" >> $GITHUB_ENV
            echo "K6_UPLOAD_THROUGHPUT=524288" >> $GITHUB_ENV
          fi
          EFFECTIVE_CLUSTER="${EVENT_CLUSTER_NODES:-${INPUT_CLUSTER_NODES}}"
          echo "Getting hoprd API token for cluster ${EFFECTIVE_CLUSTER}"
          HOPRD_API_TOKEN=$(kubectl get secret -n k6-operator-system -o json hoprd-api-tokens | jq --arg entry "${EFFECTIVE_CLUSTER}" -r '.data[$entry]' | base64 -d)
          echo "HOPRD_API_TOKEN=${HOPRD_API_TOKEN}" >> $GITHUB_ENV

      - name: Setup Load Testing environment
        run: |
          yarn install --frozen-lockfile --production=false
          yarn run setup
        working-directory: "./k6"

      - name: Run Load test
        run: |
          kubectl delete -f k6-test-run.yaml 2> /dev/null || true
          echo "Execution parameters:"
          env | grep K6_
          kubectl apply -f k6-test-run.yaml
        working-directory: "./k6"
