---
name: Merge
on:
  pull_request:
    types:
      - closed
      # - synchronize
concurrency:
  group: merge-${{ github.event.pull_request.base.ref }}
  cancel-in-progress: false
permissions:
  contents: read
  pull-requests: write
  id-token: write
jobs:
  build-binaries:
    name: Binary ${{ matrix.architecture }}
    if: github.event.pull_request.merged == true
    strategy:
      fail-fast: false
      matrix:
        include:
          - architecture: x86_64-linux
            runner: self-hosted-hoprnet-bigger
            build_command: nix build -L .#binary-hoprd-x86_64-linux
          - architecture: aarch64-linux
            runner: self-hosted-hoprnet-bigger
            build_command: nix build -L .#binary-hoprd-aarch64-linux
          - architecture: x86_64-darwin
            runner: macos-15-intel
            build_command: nix build -L .#binary-hoprd-x86_64-darwin
          - architecture: aarch64-darwin
            runner: macos-15-xlarge
            build_command: nix build -L .#binary-hoprd-aarch64-darwin
    uses: hoprnet/hopr-workflows/.github/workflows/build-binaries.yaml@build-binaries-v2
    permissions:
      contents: read
    with:
      source_branch: ${{ github.event.pull_request.base.ref }}
      version_type: pr
      architecture: ${{ matrix.architecture }}
      cachix_cache_name: hoprnet
      build_file: ./hopr/hopr-lib/Cargo.toml
      build_command: ${{ matrix.build_command }}
      binary: hoprd
      runner: ${{ matrix.runner }}
    secrets:
      gcp_service_account: ${{ secrets.GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY }}
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      gpg_private_key: ${{ secrets.GPG_HOPRNET_PRIVATE_KEY }}
  build-docker:
    name: Docker
    needs: build-binaries
    if: github.event.pull_request.merged == true
    uses: hoprnet/hopr-workflows/.github/workflows/build-docker.yaml@build-docker-v1
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    with:
      source_branch: ${{ github.event.pull_request.base.ref }}
      version_type: pr
      build_matrix: >-
        [
          {
            "runner": "self-hosted-hoprnet-bigger",
            "architecture": "x86_64-linux",
            "build_command": "nix build -L .#docker-hoprd-x86_64-linux"
          },
          {
            "runner": "self-hosted-hoprnet-bigger",
            "architecture": "aarch64-linux",
            "build_command": "nix build -L .#docker-hoprd-aarch64-linux"
          }
        ]
      cachix_cache_name: hoprnet
      docker_image_name: hoprd
      docker_image_format: skopeo
      fail_on_scan_vulnerabilities: ${{ vars.FAIL_ON_SCAN_VULNERABILITIES }}
      deployment_namespace: core-team
      deployment_label_selector: app.kubernetes.io/component=node
    secrets:
      gcp_service_account: ${{ secrets.GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY }}
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_hub_token: ${{ secrets.DOCKER_HUB_TOKEN }}
  cache_deps:
    name: Cache deps
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/cache-deps.yaml
    with:
      source_repo: ${{ github.event.pull_request.base.repo.full_name }}
      source_branch: ${{ github.event.pull_request.base.ref }}
    secrets: inherit
  docs:
    name: Docs
    needs:
      - build-docker
    uses: ./.github/workflows/build-docs.yaml
    secrets: inherit
    with:
      source_repo: ${{ github.event.pull_request.base.repo.full_name }}
      source_branch: ${{ github.event.pull_request.base.ref }}
      publish: true
  zizmor:
    name: Zizmor
    uses: ./.github/workflows/checks-zizmor.yaml
    with:
      source_repo: ${{ github.event.pull_request.base.repo.full_name || github.repository }}
      source_branch: ${{ github.event.pull_request.base.ref || github.ref }}
    secrets: inherit
  notify:
    name: Notify failure
    needs:
      - build-binaries
      - build-docker
      - docs
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify failed merge pipeline
        uses: zulip/github-actions-zulip/send-message@e4c8f27c732ba9bd98ac6be0583096dea82feea5 # v1.0.2
        with:
          api-key: ${{ secrets.ZULIP_API_KEY }}
          email: ${{ secrets.ZULIP_EMAIL }}
          organization-url: "https://hopr.zulipchat.com"
          type: "stream"
          to: "HOPRd"
          topic: "Core"
          content: |
            The merge pipeline has failed for pull request [#${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
  cleanup_actions:
    name: Cleanup Actions
    runs-on: self-hosted-hoprnet-small
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          disable-sudo: true
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - name: Checkout hoprnet repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.base.ref }}
      - name: Cleanup
        run: |
          gh extension install actions/gh-actions-cache

          REPO=${{ github.repository }}
          BRANCH="refs/pull/${{ github.event.pull_request.number }}/merge"

          echo "Fetching list of cache key"
          cacheKeysForPR=$(gh actions-cache list -R $REPO -B $BRANCH | cut -f 1 )

          ## Setting this to not fail the workflow while deleting cache keys.
          set +e
          echo "Deleting caches..."
          for cacheKey in $cacheKeysForPR
          do
            gh actions-cache delete $cacheKey -R $REPO -B $BRANCH --confirm
          done
          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
