---
#################################################################################
###                       Pipeline to merge on pull requests                  ###
#################################################################################
name: Merge
on:
  pull_request:
    types:
      - closed
      # - synchronize
concurrency:
  group: merge-${{ github.event.pull_request.base.ref }}
  cancel-in-progress: false
permissions:
  contents: read
jobs:
  build-binaries:
    name: Binary ${{ matrix.architecture }}
    if: github.event.pull_request.merged == true
    strategy:
      fail-fast: false
      matrix:
        include:
          - architecture: x86_64-linux
            runner: self-hosted-hoprnet-bigger
            build_command: nix build -L .#binary-hoprd-x86_64-linux
          - architecture: aarch64-linux
            runner: self-hosted-hoprnet-bigger
            build_command: nix build -L .#binary-hoprd-aarch64-linux
            # - architecture: x86_64-darwin
            #   runner: macos-15-intel
            #   build_command: nix build -L .#binary-hoprd-x86_64-darwin
            # - architecture: aarch64-darwin
            #   runner: macos-15-xlarge
            #   build_command: nix build -L .#binary-hoprd-aarch64-darwin
    uses: hoprnet/hopr-workflows/.github/workflows/build-binaries.yaml@build-binaries-v2
    permissions:
      contents: read
    with:
      source_branch: ${{ github.event.pull_request.base.ref }}
      version_type: pr
      architecture: ${{ matrix.architecture }}
      cachix_cache_name: hoprnet
      build_file: ./hopr/hopr-lib/Cargo.toml
      build_command: ${{ matrix.build_command }}
      binary: hoprd
      runner: ${{ matrix.runner }}
    secrets:
      gcp_service_account: ${{ secrets.GCP_SA_GITHUB_RUNNER }}
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      gpg_private_key: ${{ secrets.GPG_HOPRNET_PRIVATE_KEY }}
  build-docker:
    name: Docker
    needs: build-binaries
    if: github.event.pull_request.merged == true
    uses: hoprnet/hopr-workflows/.github/workflows/build-docker.yaml@build-docker-v1
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    with:
      source_branch: ${{ github.event.pull_request.base.ref }}
      version_type: pr
      build_matrix: >-
        [
          {
            "runner": "self-hosted-hoprnet-bigger",
            "architecture": "x86_64-linux",
            "build_command": "nix build -L .#docker-hoprd-x86_64-linux"
          },
          {
            "runner": "self-hosted-hoprnet-bigger",
            "architecture": "aarch64-linux",
            "build_command": "nix build -L .#docker-hoprd-aarch64-linux"
          }
        ]
      cachix_cache_name: hoprnet
      build_file: ./hopr/hopr-lib/Cargo.toml
      docker_image_name: hoprd
      docker_image_format: skopeo
      fail_on_scan_vulnerabilities: ${{ vars.FAIL_ON_SCAN_VULNERABILITIES }}
      deployment_namespace: core-team
      deployment_label_selector: app.kubernetes.io/component=node
    secrets:
      gcp_service_account: ${{ secrets.GCP_SA_GITHUB_RUNNER }}
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_hub_token: ${{ secrets.DOCKER_HUB_TOKEN }}
  deploy-dev:
    name: Deploy Gnosis Dev
    runs-on: self-hosted-hoprnet-small
    needs: build-docker
    if: github.event.pull_request.merged == true
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Restart Hoprd
        uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # v3.0.0
        with:
          token: ${{ secrets.GNOSIS_GITHUB_WORKFLOW_TOKEN }}
          repository: gnosis/gnosis_vpn-infrastructure
          event-type: restart_hoprd
          client-payload: |-
            {
              "environment": "dev"
            }
  cache_deps:
    name: Cache deps
    if: github.event.pull_request.merged == true
    runs-on: self-hosted-hoprnet-small
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Cache dependencies
        uses: hoprnet/hopr-workflows/actions/nix-action@c2aca7e56d25c4a786049ccf816c7f1af8721de8 # nix-action-v1
        with:
          source_branch: ${{ github.event.pull_request.base.ref }}
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          command: |
            set -e
            cat >> .cargo/config.toml << TOML
            [source.hopr-cargo-registry-cache]
            registry = "sparse+${PRIVATE_CARGO_REGISTRY_PROXY_URL}"

            [source.crates-io]
            replace-with = "hopr-cargo-registry-cache"
            TOML
            nix develop -c cargo fetch
        env:
          PRIVATE_CARGO_REGISTRY_PROXY_URL: ${{ secrets.PRIVATE_CARGO_REGISTRY_PROXY_URL }}
  docs:
    name: Docs
    if: github.event.pull_request.merged == true
    needs:
      - build-docker
    runs-on: self-hosted-hoprnet-bigger
    timeout-minutes: 60
    permissions:
      contents: write
    steps:
      - name: Build docs
        uses: hoprnet/hopr-workflows/actions/nix-action@c2aca7e56d25c4a786049ccf816c7f1af8721de8 # nix-action-v1
        with:
          source_branch: ${{ github.event.pull_request.base.ref }}
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          command: |
            set -e
            RUSTDOCFLAGS="-D warnings" nix develop -c cargo doc --no-deps --document-private-items
            nix build -L .#docs
      - name: Increase git buffer size
        run: git config --global http.postBuffer 524288000
      - name: Deploy
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./result/share/doc/
          force_orphan: true
  coverage:
    name: Coverage
    if: github.event.pull_request.merged == true
    uses: hoprnet/hopr-workflows/.github/workflows/tests.yaml@268553d7984344080e3dc65eb92778c9103af7ec # workflow-tests-v3
    with:
      source_branch: ${{ github.event.pull_request.base.ref }}
      unit_tests: false
      integration_tests: false
      nightly_tests: false
      benchmarks: false
      unit_coverage: true
      integration_coverage: true
      unconditional: true
      unit_coverage_command: |
        nix build -L .#coverage-unit
        cp result coverage.lcov
      integration_coverage_command: |
        nix develop .#coverage -c env NEXTEST_HIDE_PROGRESS_BAR=1 cargo llvm-cov nextest \
          --workspace \
          --test '*' \
          --lcov --output-path coverage.lcov \
          -j 1
      runner: self-hosted-hoprnet-bigger
    secrets:
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
  notify:
    name: Notify failure
    needs:
      - build-binaries
      - build-docker
      - coverage
      - docs
    if: ${{ always() && github.event.pull_request.merged == true && !success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify failed merge pipeline
        uses: zulip/github-actions-zulip/send-message@e4c8f27c732ba9bd98ac6be0583096dea82feea5 # v1.0.2
        with:
          api-key: ${{ secrets.ZULIP_API_KEY }}
          email: ${{ secrets.ZULIP_EMAIL }}
          organization-url: "https://hopr.zulipchat.com"
          type: "stream"
          to: "HOPRd"
          topic: "Core"
          content: |
            The merge pipeline has failed for pull request [#${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
  cleanup_actions:
    name: Cleanup Actions
    runs-on: self-hosted-hoprnet-small
    permissions:
      actions: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          disable-sudo: true
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - name: Checkout hoprnet repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.base.ref }}
      - name: Cleanup
        run: |
          gh extension install actions/gh-actions-cache

          REPO=${{ github.repository }}
          BRANCH="refs/pull/${{ github.event.pull_request.number }}/merge"

          echo "Fetching list of cache key"
          cacheKeysForPR=$(gh actions-cache list -R $REPO -B $BRANCH | cut -f 1 )

          ## Setting this to not fail the workflow while deleting cache keys.
          set +e
          echo "Deleting caches..."
          for cacheKey in $cacheKeysForPR
          do
            gh actions-cache delete $cacheKey -R $REPO -B $BRANCH --confirm
          done
          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
