---
#################################################################################
###                       Pipeline to merge on pull requests                  ###
#################################################################################
name: Merge
on:
  pull_request:
    types:
      - closed
      # - synchronize
    branches:
      - master
      - 'release/*'
concurrency:
  group: merge-${{ github.event.pull_request.base.ref }}
  cancel-in-progress: false
permissions:
  contents: read
jobs:
  cache_deps:
    name: Cache deps
    if: github.event.pull_request.merged == true
    runs-on: depot-ubuntu-24.04-4
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Cache dependencies
        uses: hoprnet/hopr-workflows/actions/nix-action@ade4bbd75f7204255c61d19c23f67d3da221e7d2 # nix-action-v1
        with:
          source_branch: ${{ github.event.pull_request.base.ref }}
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          command: |
            set -e
            cat >> .cargo/config.toml << TOML
            [source.hopr-cargo-registry-cache]
            registry = "sparse+${PRIVATE_CARGO_REGISTRY_PROXY_URL}"

            [source.crates-io]
            replace-with = "hopr-cargo-registry-cache"
            TOML
            nix develop -c cargo fetch
        env:
          PRIVATE_CARGO_REGISTRY_PROXY_URL: ${{ secrets.PRIVATE_CARGO_REGISTRY_PROXY_URL }}
  docs:
    name: Docs
    if: github.event.pull_request.merged == true
    runs-on: depot-ubuntu-24.04-4
    timeout-minutes: 60
    permissions:
      contents: write
    steps:
      - name: Build docs
        uses: hoprnet/hopr-workflows/actions/nix-action@ade4bbd75f7204255c61d19c23f67d3da221e7d2 # nix-action-v1
        with:
          source_branch: ${{ github.event.pull_request.base.ref }}
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          command: |
            set -e
            RUSTDOCFLAGS="-D warnings" nix develop -c cargo doc --no-deps --document-private-items
            nix build -L .#docs
      - name: Increase git buffer size
        run: git config --global http.postBuffer 524288000
      - name: Deploy
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./result/share/doc/
          force_orphan: true
  notify:
    name: Notify failure
    needs:
      - docs
    if: ${{ always() && github.event.pull_request.merged == true && !success() }}
    runs-on: depot-ubuntu-24.04
    steps:
      - name: Notify failed merge pipeline
        uses: zulip/github-actions-zulip/send-message@f675f2b4eb2a95fae974215476dcb7ad8dfeff6b # v2.0.2
        with:
          api-key: ${{ secrets.ZULIP_API_KEY }}
          email: ${{ secrets.ZULIP_EMAIL }}
          organization-url: "https://hopr.zulipchat.com"
          type: "stream"
          to: "HOPRd"
          topic: "Core"
          content: |
            The merge pipeline has failed for pull request [#${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
  cleanup_actions:
    name: Cleanup Actions
    runs-on: depot-ubuntu-24.04
    permissions:
      actions: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          disable-sudo: true
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - name: Checkout hoprnet repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.base.ref }}
      - name: Cleanup
        run: |
          gh extension install actions/gh-actions-cache

          REPO=${{ github.repository }}
          BRANCH="refs/pull/${{ github.event.pull_request.number }}/merge"

          echo "Fetching list of cache key"
          mapfile -t cacheKeysForPR < <(gh actions-cache list -R "$REPO" -B "$BRANCH" --json key --jq '.[].key')

          ## Setting this to not fail the workflow while deleting cache keys.
          set +e
          echo "Deleting caches..."
          for cacheKey in "${cacheKeysForPR[@]}"
          do
            gh actions-cache delete "$cacheKey" -R "$REPO" -B "$BRANCH" --confirm
          done
          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
