---
################################################################################
# Pull request pipeline for hoprnet
#
# Dispatches checks, tests, and builds concurrently.
################################################################################
name: PR

on:
  merge_group:
    types: [checks_requested]
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  actions: read
  contents: read

concurrency:
  group: ${{ github.event.pull_request.head.ref || github.ref_name }}-pr
  cancel-in-progress: true

jobs:
  checks:
    name: Check
    uses: ./.github/workflows/checks.yaml
    with:
      source_repo: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
      source_branch: ${{ github.event.pull_request.head.ref || github.ref }}
    secrets:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

  tests:
    name: Test
    uses: ./.github/workflows/tests.yaml
    with:
      source_repo: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
      source_branch: ${{ github.event.pull_request.head.ref || github.ref }}
    secrets:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    with:
      source_repo: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
      source_branch: ${{ github.event.pull_request.head.ref || github.ref }}
      labels: ${{ format('{0},', join(github.event.pull_request.labels.*.name, ',')) }}
    secrets:
      GCP_SA_GITHUB_RUNNER: ${{ secrets.GCP_SA_GITHUB_RUNNER }}
      GH_RUNNER_TOKEN: ${{ secrets.GH_RUNNER_TOKEN }}
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
      GPG_HOPRNET_PRIVATE_KEY: ${{ secrets.GPG_HOPRNET_PRIVATE_KEY }}
