---
#################################################################################
# Manual pipeline to promote a release name to have its own branch
#################################################################################
name: Promote Release

on:
  workflow_dispatch:
    inputs:
      tag_release_name:
        type: string
        required: true
        description: 'Release name for tag'
      new_release_name:
        type: string
        required: true
        description: 'New release name'
      tag_name:
        type: string
        required: true
        description: 'Git tag from which the release branch fork (v3.0.0)'

concurrency:
  group: promote-release
  cancel-in-progress: true

jobs:
  promote_release:
    name: Promote Release
    runs-on: self-hosted-hoprnet-small
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          disable-sudo: true
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout hoprnet repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags
          persist-credentials: true # required for gh cli to do push
          token: ${{ secrets.GH_RUNNER_TOKEN }} # Needs to use a different token than GITHUB_TOKEN to be able to push to protected branches
          ref: master

      - name: Promote release
        run: |
          set -x
          echo "Checkout to tag revision"
          if ! git tag -l "${{ github.event.inputs.tag_name }}" | grep -xF "${{ github.event.inputs.tag_name }}"; then
            echo "Git tag ${{ github.event.inputs.tag_name }} does not exists"
            exit 1
          fi
          echo "Create new branch or reuse an existing branch"
          current_version=$(grep -E '^version\s*=' hopr/hopr-lib/Cargo.toml | awk -F\" '{print $2}')
          IFS='-' read -a current_version_splitted <<<"${current_version}"
          current_version_without_rc="${current_version_splitted[0]}"
          IFS='.' read -r major_version minor_version patch_version <<< "${current_version_without_rc}"
          
          release_branch_name="release/${major_version}.${minor_version}"
          if git branch -al "${release_branch_name}" | grep -F "${release_branch_name}"; then
            echo "Branch ${release_branch_name} already exists. Skipping promotion..."
            exit 0
          else
            git checkout "${{ github.event.inputs.tag_name }}"
            git checkout -b "${release_branch_name}"
            git push --set-upstream origin "${release_branch_name}"
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_RUNNER_TOKEN }}
