---
#################################################################################
# Manual pipeline to clone a docker image tag based on other docker image tag
#################################################################################
name: Publish Release

on:
  workflow_dispatch:
    inputs:
      from_tag:
        type: string
        required: true
        default: "kaunas"
        description: "Source tag name"
      to_tag:
        type: string
        required: true
        description: "Target tag name"
        default: "stable"

concurrency:
  group: publish-release
  cancel-in-progress: true

jobs:
  publish-release:
    name: Publish Release
    runs-on: depot-ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          disable-sudo: true
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Setup GCP
        id: gcp
        uses: hoprnet/hopr-workflows/actions/setup-gcp@12c56020e16036982e6cc529848edeedfc705865 # master
        with:
          google_credentials: ${{ secrets.GCP_SA_GITHUB_RUNNER }}
          login_artifact_registry: 'true'
          install_sdk: 'true'

      - name: Tag docker images with release name
        run: |
          images=(hoprd)
          for image in "${images[@]}";
          do
            echo "Tagging ${image}"
            gcloud artifacts docker tags add \
              "${DOCKER_IMAGE_REGISTRY}/${image}:${FROM_TAG}" \
              "${DOCKER_IMAGE_REGISTRY}/${image}:${TO_TAG}"
          done
        env:
          DOCKER_IMAGE_REGISTRY: ${{ vars.DOCKER_IMAGE_REGISTRY }}
          FROM_TAG: ${{ github.event.inputs.from_tag }}
          TO_TAG: ${{ github.event.inputs.to_tag }}
