---
#################################################################################
# Pipeline triggered on every pull request to run unit and smoke tests
#################################################################################
name: Test

env:
  RUST_BACKTRACE: "1"
  FOUNDRY_PROFILE: ci

on:
  merge_group:
    types: [checks_requested]
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

concurrency:
  group: ${{ github.event.pull_request.head.ref || github.ref_name }}-${{ github.workflow}}
  cancel-in-progress: true

jobs:
  tests-unit:
    name: Unit Tests
    runs-on: self-hosted-hoprnet-bigger
    timeout-minutes: 60
    env:
      CI: "true"
    steps:
      - name: Run unit tests
        uses: hoprnet/hopr-workflows/actions/nix-action@nix-action-v1
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
          use_cachix: "true"
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          command: nix build -L .#hopr-test-unit

  tests-integration:
    name: Integration Tests
    runs-on: self-hosted-hoprnet-bigger
    timeout-minutes: 60
    env:
      CI: "true"
    steps:
      - name: Run integration tests
        uses: hoprnet/hopr-workflows/actions/nix-action@nix-action-v1
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
          use_cachix: "true"
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          command: nix develop -c cargo test --test '*' -- --test-threads=1

  tests-unit-nightly:
    name: Unit Tests Nightly
    runs-on: self-hosted-hoprnet-bigger
    timeout-minutes: 60
    env:
      CI: "true"
    steps:
      - name: Set up Google Cloud Credentials
        id: auth
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        if: ${{ !env.ACT }}
        with:
          token_format: "access_token"
          credentials_json: ${{ secrets.GCP_SA_GITHUB_RUNNER }}

      - name: Run unit tests with nightly
        uses: hoprnet/hopr-workflows/actions/nix-action@nix-action-v1
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
          use_cachix: "true"
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          command: nix build -L .#hopr-test-nightly

  build-benchmarks:
    name: Build Benchmarks
    runs-on: self-hosted-hoprnet-bigger
    timeout-minutes: 20
    if: github.event_name == 'merge_group'
    steps:
      - name: Build benchmarks
        uses: hoprnet/hopr-workflows/actions/nix-action@nix-action-v1
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
          use_cachix: "true"
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          command: nix build .#hoprd-bench-build
