---
#################################################################################
# Pipeline triggered on every pull request to run unit and smoke tests
#################################################################################
name: Test

env:
  RUST_BACKTRACE: "1"
  FOUNDRY_PROFILE: ci

on:
  merge_group:
    types: [checks_requested]
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

concurrency:
  group: ${{ github.event.pull_request.head.ref || github.ref_name }}-${{ github.workflow}}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: self-hosted-hoprnet-bigger
    timeout-minutes: ${{ matrix.timeout }}
    env:
      CI: "true"
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Unit Tests
            timeout: 60
            command: nix build -L .#hopr-test-unit
          - name: Integration Tests
            timeout: 60
            command: nix develop -c cargo test --test '*' -- --test-threads=1
          - name: Unit Tests Nightly
            timeout: 60
            command: nix build -L .#hopr-test-nightly
    steps:
      - name: Run ${{ matrix.name }}
        uses: hoprnet/hopr-workflows/actions/nix-action@nix-action-v1
        with:
          source_branch: ${{ github.event.pull_request.head.ref || github.ref }}
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          command: ${{ matrix.command }}

  build-benchmarks:
    name: Build Benchmarks
    runs-on: self-hosted-hoprnet-bigger
    timeout-minutes: 20
    if: github.event_name == 'merge_group'
    steps:
      - name: Build benchmarks
        uses: hoprnet/hopr-workflows/actions/nix-action@nix-action-v1
        with:
          source_branch: ${{ github.event.pull_request.head.ref || github.ref }}
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          command: nix build .#hoprd-bench-build
